language: nix

addons:
  ssh_known_hosts: garbas.si

env:
- PKGS_SET=flask
- PKGS_SET=django
- PKGS_SET=pyramid
- PKGS_SET=science

script:
- if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
    nix-shell update.nix --pure;
  fi
- if [ "$TRAVIS_PULL_REQUEST" != "true" -a "$TRAVIS_BRANCH" = "master" ]; then
    make pypi2nix $PKGS_SET;
    mkdir nars/;
    nix-push --dest "$PWD/nars/" --force ./result-$PKGS_SET;
  fi

before_install:
- echo 'binary-caches = https://cache.nixos.org/ https://travis.garbas.si/nixpkgs-python/' | sudo tee -a /etc/nix/nix.conf > /dev/null
- openssl aes-256-cbc -K $encrypted_1ae048d151c2_key -iv $encrypted_1ae048d151c2_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa


after_success:
- rsync -avh --ignore-existing $TRAVIS_BUILD_DIR/nars/ travis@garbas.si:/var/travis/nixpkgs-python/
- git remote set-url --push origin git@github.com:garbas/nixpkgs-python.git
- git config user.name 'travis'
- git config user.email 'travis@garbas.si'
- git add --all .
- git commit -m 'travis: update for $PKGS_SET [ci skip]'
- git push origin $TRAVIS_BRANCH
