language: nix
addons:
  ssh_known_hosts: floki.garbas.si
env:
- PKGS_SET=flask
- PKGS_SET=django
- PKGS_SET=pyramid
- PKGS_SET=scipy
script:
- if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
    nix-shell update.nix --pure;
  fi
- if [ "$TRAVIS_PULL_REQUEST" != "true" -a "$TRAVIS_BRANCH" = "master" ]; then
    make pypi2nix $PKGS_SET;
    mkdir nars/;
    nix-push --dest "$PWD/nars/" --force ./result-$PKGS_SET;
  fi
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
before_install:
- openssl aes-256-cbc -K $encrypted_1ae048d151c2_key -iv $encrypted_1ae048d151c2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avh --ignore-existing $TRAVIS_BUILD_DIR/nars/ travis@floki.garbas.si:/var/travis/nixpkgs-python/
  on:
    branch: master
